=head1 PKGBUILD for configure-bashdocserver-extra

    pkgname='configure-bashdocserver-extra'
    pkgdesc='Configuration package for a bashdoc webserver on port 8080'
    pkgver='1.0.0'
    pkgrel=1
    arch=any
    depends=(
        'configure-bashdocserver'
    )
    sources=(
        'nginx.conf.holoscript'
    )
    install='configure-bashdocserver-extra.install'

    package() {
        install -D -m 0755 nginx.conf.holoscript \
            "${pkgdir}/holo/repo/20-alternate-port/etc/nginx/nginx.conf.holoscript"
    }

=head1 configure-bashdocserver-extra.install

This is identical to the previous C<.install> file.

    post_install() {
        holo apply
    }
    post_upgrade() {
        holo apply
    }
    post_remove() {
        holo apply
    }

=head1 nginx.conf.holoscript

    #!/bin/sh
    sed 's/listen\s*80;/listen 8080;/'
