=head1 PKGBUILD for configure-bashdocserver

Not much has changed from the previous example, except that we're installing
the configuration file.

    pkgname='configure-bashdocserver'
    pkgdesc='Configuration package for a bashdoc webserver'
    pkgver='1.0.0'
    pkgrel=1
    arch=any
    depends=(
        'nginx'
    )
    sources=(
        'nginx.conf'
    )

    package() {
        mkdir -p "${pkgdir}/etc/systemd/system/multi-user.target.wants/"
        ln -sf /usr/lib/systemd/system/nginx.service \
            "${pkgdir}/etc/systemd/system/multi-user.target.wants/nginx.service"

        install -D -m 0644 nginx.conf "${pkgdir}/etc/nginx/nginx.conf"
    }

=head1 nginx.conf

Really not much to see here, this is mostly the default configuration with some
values pasted in.

    user http;
    worker_processes 1;
    events {
        worker_connections 1024;
    }

    http {
        include mime.types;
        default_type application/octet-stream;

        sendfile on;
        keepalive_timeout 65;

        server {
            listen      80;
            server_name bashdoc.local;

            location / {
                root  /usr/share/doc/bash;
                index bash.html;
            }

            error_page 500 502 503 504  /nginx_50x.html;
            location = /nginx_50x.html {
                root /etc/nginx/pages;
            }
        }
    }

